{% set name = "git-annex" %}
{% set version = "7.20190219" %}
{% set sha256 = "82f3c10fe96141b1564bfc894a36c0e53bdf6843f09782c380d1a616bf96c104" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-use-ghc-8.4.2-enable-magicmime-and-dbus-add-wcwidth-.patch

build:
  number: 13
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack >=1.9.3
    - perl
    - coreutils
    - binutils
    - chrpath
  host:
    - gmp
    - zlib
    - ncurses
    - libmagic
    - libgsasl
    - libxml2
    - gnutls
    - sqlite
    - dbus
  run:
    - rsync
    - git

test:
  commands:
    - git-annex version
    - git-annex test

about:
  home: http://git-annex.branchable.com
  license: GPL-3
  summary: A tool for managing large files with git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
