{% set name = "git-annex" %}

#
# This recipe builds two variants of the git-annex conda package: the standard one, and a "nodep" (no-dependencies) one.
# The nodep package installs the standalone version of git-annex ( https://git-annex.branchable.com/install/Linux_standalone/ ),
# which has no dependencies; it can be used to install git-annex into conda environments that include packages which conflict
# with some dependencies of git-annex.  The standard (non-nodep) version is preferred; the nodep version should only be used
# in case of unresolvable dependency conflicts.
#

{% set version = "8.20201007" %}  # [not nodep]
{% set version = "8.20200810" %}  # [nodep]
{% set sha256 = "0af92007388dbb0cbd02dc3d1565b6712bcae56de7089f31dfdff63909f3216c" %}  # [not nodep]
{% set sha256 = "7f41d56041da79110aee971cb9f413a7e9f87baca3f3982c3595d0d8abf382c7" %}  # [nodep]
{% set size = "55064901" %}  # [nodep]

{% set version = "8.20201007+git115-g65c168743" %}  # [nodep and win]
{% set sha256 = "904f7a4a7e1c40d0fba5d9f4097894ce0588d651f947ec689ae90fe151453ca7" %}  # [nodep and win]

{% set version = "TODO" %}  # [nodep and osx]
{% set sha256 = "TODO" %}  # [nodep and osx]

{% set nodep = True %}  # [nodep]
{% set nodep = False %}  # [not nodep]
{% set linux = True %}  # [linux]
{% set linux = False %}  # [not linux]
{% set win = True %}  # [win]
{% set win = False %}  # [not win]
{% set osx = True %}  # [osx]
{% set osx = False %}  # [not osx]

{% set build = 2 %}
# prioritize non-nodep variant via build number
{% if not nodep %}
{% set build = build + 100 %}
{% endif %}

#
# This recipe builds GHC, the Haskell compiler used to compile git-annex, from source, then uses it
# to compile git-annex.  It would be better to separate GHC into its own conda-forge package, and have the
# git-annex recipe depend on that, but I could not make that work.  Hopefully, someone with a better
# understanding of ghc and conda-forge can eventually rewrite the recipes in the more proper way.
#
# For related discussions see
# https://github.com/conda-forge/git-annex-feedstock/pull/44
# https://github.com/bioconda/bioconda-recipes/pull/16008
#

{% set ghc_src_version = "8.8.4" %}
{% set ghc_src_sha256 = "f0505e38b2235ff9f1090b51f44d6c8efd371068e5a6bb42a2a6d8b67b5ffc2d" %}
{% set ghc_bootstrap_version = "8.4.2" %}
{% set ghc_bootstrap_linux_sha256 = "28c31489ed9a83af4400685ec8bc72a6d43d08958d75b2dc35d29a894a5c9d93" %}

package:
  name: {{ name }}
  version: {{ version.replace('+', '.').replace('-', '.') }}

{% if not nodep %}
source:
  - url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: git_annex_main
    patches:
      - 0001-add-fdo-notify.patch

  - url: https://downloads.haskell.org/~ghc/{{ ghc_bootstrap_version }}/ghc-{{ ghc_bootstrap_version }}-x86_64-centos67-linux.tar.xz  # [linux]
    sha256: {{ ghc_bootstrap_linux_sha256 }}  # [linux]
    folder: ghc_bootstrap  # [linux]

  - url: https://downloads.haskell.org/~ghc/{{ ghc_src_version }}/ghc-{{ ghc_src_version }}-src.tar.xz
    sha256: {{ ghc_src_sha256 }}
    folder: ghc_src

build:
  number: {{ build }}
  skip: True  # TEMP 
  string: "alldep_h{{ PKG_HASH }}_{{ build }}"  # [not nodep]
  script: ${RECIPE_DIR}/build_nodepFalse.sh

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack
    - perl
    - coreutils
    - binutils
    - findutils
    - pkg-config
    - xz
    - make
    - automake
    - autoconf
    - libtool
    - bzip2
    - ncurses
    - libffi
    - libxml2
  host:
    - gmp
    - zlib
    - ncurses
    - libmagic
    - sqlite
    - dbus
    - libffi
    - libiconv
    - openssh
    - lsof
    - rsync
  run:
    - rsync
    - git >=2.22
    - curl
    - openssh
    - lsof
{% endif %}

{% if nodep %}
{% if linux %}
source:
  - url: http://archive.org/download/git-annex-builds/SHA256E-s{{ size }}--{{ sha256 }}.tar.gz
#  - url: https://downloads.kitenet.net/git-annex/autobuild/amd64/git-annex-standalone-amd64.tar.gz 
    sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: True  # TEMP
  string: "nodep_h{{ PKG_HASH }}_{{ build }}"
  script: ${RECIPE_DIR}/build_nodepTrue.sh
  ignore_prefix_files: True
  detect_binary_files_with_prefix: False
  binary_relocation: False
{% endif %}

{% if win %}
source:
  - url: http://datasets.datalad.org/datalad/packages/windows/{{ name }}-installer_{{ version }}_x64.exe
    sha256: {{ sha256 }}
requirements:
  build:
    - 7zip
build:
  number: {{ build }}
  skip: True  # [not win]
  string: "nodep_h{{ PKG_HASH }}_{{ build }}"
  script: "%RECIPE_DIR%\\build_nodepTrue_win.bat"
{% endif %}

{% if osx %}
source:
  # later - url: http://datasets.datalad.org/datalad/packages/osx/{{ name }}-installer_{{ version }}_x64.dmg
  - url: https://downloads.kitenet.net/git-annex/autobuild/x86_64-apple-yosemite/git-annex.dmg
    sha256: "c69accb64990664a40f4f13778f2330a17a506628c8c4ba4a57710c7a3f14840"
build:
  number: {{ build }}
  skip: True  # [not osx]
  string: "nodep_h{{ PKG_HASH }}_{{ build }}"
  script: ${RECIPE_DIR}/build_nodepTrue_osx.sh
{% endif %}
{% endif %}

test:
  commands:
    - git-annex version | grep {{ version }}
    - git-annex test
  downstreams:
    - annexremote
    - datalad=0.13.4  # [not nodep]

about:
  home: https://git-annex.branchable.com
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: A tool for managing large files with git
  description: |
    git-annex allows managing files with git, without checking the file contents into git.
    It is useful when dealing with files larger than git can currently easily handle.
    The contents can be stored locally or in various remote repositories; git-annex tracks
    which contents is stored where.
  doc_url: https://git-annex.branchable.com
  dev_url: http://source.git-annex.branchable.com/?p=source.git;a=summary

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
