{% set name = "git-annex" %}
{% set version = "7.20190219" %}
{% set sha256 = "e91a9caeb202d8f27958d22d040ebef9bd5af3b003302873f02bcb1a48778118" %}
{% set size = "65427380" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz_
  url: https://downloads.kitenet.net/.git/annex/objects/g3/Q0/SHA256E-s{{ size }}--{{ sha256 }}.tar.gz/SHA256E-s{{ size }}--{{ sha256 }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or osx]
  binary_relocation: False

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - git >=2
  run:
    - git >=2
  
test:
  requires:
    - git >=2

about:
  home: https://git-annex.branchable.com
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: 'Version control large files with git without storing them'
  description: |
    git-annex lets you use git to track large, distributed files without checking them into git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
