{% set name = "git-annex" %}
{% set version = "7.20190507" %}
{% set sha256 = "c403a750a08625a4572681bf646d75ffdd3f7cef3e3aa509e4861a8db4c7904e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack >=1.9.3
    - perl
    - coreutils  # [not win]
    - binutils  # [not win]
  host:
    - gmp  # [not win]
    - zlib
    - ncurses  # [not win]
    - libmagic  # [not win]
    - libxml2
    - sqlite
    - dbus  # [not win]
  run:
    - git
    - libmagic  # [not win]
    - rsync  # [not win]
    - curl

test:
  requires:
    - datalad  # [not win]
    - nose  # [not win]
  commands:
    - git-annex version
    - git-annex test
    - datalad test  # [not win]

about:
  home: http://git-annex.branchable.com
  license: GPL-3
  summary: A tool for managing large files with git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
