{% set name = "git-annex" %}
{% set version = "6.20180626" %}
{% set sha256 = "f8b80e861c033605a62dffc0a97ffae5df506eaa238bcaae31a20e486eea036f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True  # [win or osx]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - perl
    - git >=2
    - stack
    - ncurses
    - libmagic >=5.30
    - libgsasl
    - gmp
    - rsync
    - libffi
    - gnutls
    - libxml2
    - sqlite
    - chrpath  # [linux]
  run:
    - perl
    - git >=2
    - rsync
    - ncurses
    - libmagic >=5.30
    - libgsasl
    - gmp
    - libffi
    - gnutls
    - libxml2
    - sqlite
    - chrpath  # [linux]

about:
  home: https://git-annex.branchable.com
  license: GPLv3
  license_family: GPL
  license_file: COPYRIGHT
  summary: 'Version control large files with git without storing them'
  description: |
    git-annex lets you use git to track large, distributed files without checking them into git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
