{% set name = "git-annex" %}
{% set version = "7.20181105" %}
{% set sha256 = "83df8691964aea5c59e901d639d18fe96e2073b93d5cff1adc9931fddc4a044a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - toolchain
    - pkg-config
    - perl
    - git >=2
    - stack
    - ncurses 5.9
    - libmagic >=5.30
    - libgsasl
    - gmp 6.1.*
    - rsync
    - libffi
    - gnutls
    - libxml2 2.9.*
    - sqlite 3.20.*
    - chrpath  # [linux]
  run:
    - perl
    - git >=2
    - rsync
    - ncurses 5.9
    - libmagic >=5.30
    - libgsasl
    - gmp 6.1.*
    - libffi
    - gnutls
    - libxml2 2.9.*
    - sqlite 3.20.*

about:
  home: https://git-annex.branchable.com
  license: GPLv3
  license_family: GPL
  license_file: COPYRIGHT
  summary: 'Version control large files with git without storing them'
  description: |
    git-annex lets you use git to track large, distributed files without checking them into git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
