{% set name = "git-annex" %}
{% set version = "7.20190503" %}
{% set sha256 = "442b5ef8dbcc4b9b0ab0ab30c497ed90b0422bfb6ad6306a600a5607d184ff88" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack >=1.9.3
    - perl
    - coreutils
    - binutils
  host:
    - gmp
    - zlib
    - ncurses
    - libmagic
    - libxml2
    - sqlite
    - dbus
  run:
    - libmagic
    - rsync
    - git

test:
  requires:
    - datalad
    - nose
  commands:
    - git-annex version
    - git-annex test
    - datalad test

about:
  home: http://git-annex.branchable.com
  license: GPL-3
  summary: A tool for managing large files with git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
