{% set name = "git-annex" %}
{% set version = "7.20200309" %}  # [v7]
{% set version = "8.20200309" %}  # [not v7]
{% set sha256 = "c04d361415f273a076ab59fbc5c1a860835ab0b5732d44027fe6695eecf2e3da" %}  # [not nodep and v7]
{% set sha256 = "e5868490fc710b0df4e1960a544dbd6cde55bb8f04624bc8c38ce50265004bfa" %}  # [not nodep and not v7]
{% set sha256 = "d7d22864ecff78db2087ac2560c3c900f7ed88413359426f1e85c4f51a7de494" %}  # [nodep]

{% set nodep = True %}  # [nodep]
{% set nodep = False %}  # [not nodep]

{% set build = 0 %}
# prioritize non-nodep variant via build number
{% if not nodep %}
{% set build = build + 100 %}
{% endif %}

#
# This recipe builds GHC, the Haskell compiler used to compile git-annex, from source, then uses it
# to compile git-annex.  It would be better to separate GHC into its own recipe, and have the
# git-annex recipe depend on that, but I could not make that work.  Hopefully someone with a better
# understanding of ghc and conda-forge can eventually rewrite the recipes in the more proper way.
#
# For related discussions see
# https://github.com/conda-forge/git-annex-feedstock/pull/44
# https://github.com/bioconda/bioconda-recipes/pull/16008
#

{% set ghc_src_version = "8.6.5" %}
{% set ghc_src_sha256 = "4d4aa1e96f4001b934ac6193ab09af5d6172f41f5a5d39d8e43393b9aafee361" %}
{% set ghc_bootstrap_version = "8.4.2" %}
{% set ghc_bootstrap_linux_sha256 = "28c31489ed9a83af4400685ec8bc72a6d43d08958d75b2dc35d29a894a5c9d93" %}

package:
  name: {{ name }}
  version: {{ version }}

{% if not nodep %}
source:
  - url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: git_annex_main
    patches:
      - 0001-added-extra-deps-for-fdo-notify-and-magic.patch  # [v7]
      - 0001-new-patch-to-add-fdo-notify-and-magic.patch  # [not v7]

  - url: https://downloads.haskell.org/~ghc/{{ ghc_bootstrap_version }}/ghc-{{ ghc_bootstrap_version }}-x86_64-centos67-linux.tar.xz  # [linux]
    sha256: {{ ghc_bootstrap_linux_sha256 }}  # [linux]
    folder: ghc_bootstrap

  - url: https://downloads.haskell.org/~ghc/{{ ghc_src_version }}/ghc-{{ ghc_src_version }}-src.tar.xz
    sha256: {{ ghc_src_sha256 }}
    folder: ghc_src

build:
  number: {{ build }}
  skip: True  # [not linux]
  string: "h{{ PKG_HASH }}_{{ build }}"  # [not nodep]
  script: ${RECIPE_DIR}/build_nodepFalse.sh

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack >=1.9.3
    - perl
    - coreutils
    - binutils
    - pkg-config
    - xz
    - automake
    - autoconf
    - libtool
    - bzip2
    - ncurses
    - libffi
    - libxml2
  host:
    - gmp
    - zlib
    - ncurses
    - libmagic
    - sqlite
    - dbus
    - libffi
    - libiconv
    - openssh
    - lsof
    - rsync
    - gsasl
  run:
    - rsync
    - git >=2.22
    - curl
    - openssh
    - lsof
{% endif %}

{% if nodep %}
source:
  - url: https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz
    sha256: {{ sha256 }}
    patches:
      - 0001-fix-long-paths-in-locales.patch

build:
  number: {{ build }}
  skip: True  # [not linux]
  string: "nodep_h{{ PKG_HASH }}_{{ build }}"
  script: ${RECIPE_DIR}/build_nodepTrue.sh
{% endif %}

test:
  commands:
    - git-annex version
    - git-annex test

about:
  home: http://git-annex.branchable.com
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: A tool for managing large files with git
  description: |
    git-annex allows managing files with git, without checking the file contents into git.
    It is useful when dealing with files larger than git can currently easily handle.
    The contents can be stored locally or in various remote repositories; git-annex tracks
    which contents is stored where.

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
