{% set name = "git-annex" %}
{% set version = "7.20190708" %}
{% set sha256 = "32d27f64c5d26a3c0c1f3fd445791f1e105b216cb7a4940ee915ddccf53045a3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack >=1.9.3
    - perl
    - coreutils
    - binutils
  host:
    - gmp
    - zlib
    - ncurses
    - libmagic
    - libxml2
    - sqlite
    - dbus
  run:
    - git
    - libmagic
    - rsync
    - curl

test:
  requires:
    - datalad
    - nose
  commands:
    - git-annex version
    - git-annex test
    - datalad test

about:
  home: http://git-annex.branchable.com
  license: GPL-3
  summary: A tool for managing large files with git

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
