{% set name = "git-annex" %}
{% set version = "7.20190708" %}
{% set sha256 = "32d27f64c5d26a3c0c1f3fd445791f1e105b216cb7a4940ee915ddccf53045a3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack >=1.9.3
    - perl
    - coreutils
    - binutils
  host:
    - gmp
    - zlib
    - ncurses
    - libmagic
    - libxml2
    - sqlite
    - dbus
  run:
    - git
    - libmagic
    - rsync
    - curl

test:
  requires:
    - datalad
    - nose
  commands:
    - git-annex version
    - git-annex test
    - datalad test

about:
  home: http://git-annex.branchable.com
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: A tool for managing large files with git
  description: |
    git-annex allows managing files with git, without checking the file contents into git.
    It is useful when dealing with files larger than git can currently easily handle.
    The contents can be stored locally or in various remote repositories; git-annex tracks
    which contents is stored where.

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
