appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Vjhto6MvC2c5iYi37HtaEkqLs5P+1pJUizgls79ZPSjluakzZmtbD39W6Grtc1toyYegWKlrulYU1LzDUO/zh8VOUYH+Z7ff7GgxUItaOE6afyLmq0U6Hi2yzEbn8GEZpTRWkRrtnbSLvZlBkrSGb5CeDizxf1FwKGBBwGRWJ9GcHaiZruo8ZEL+HwlVlavmzlp0DfWre6X1mjS2nhcCaW3GgylBb9mKayxp0zYNAMyO6vH5UUoNvFJM6ywpbm+OP4HveVUAD/YDO3BUfa24w+DrFMr4m1oobaIgksXvl9Eh0Bu1l5rSrWL012KGaeMFz1jw/EnenhJsE/XkUPXcuDLR5YNVz45Vs65SlrsMFWVtZ9UJg9E5HCoLpjZXkZUZV7UyiIAsB0MOrhMdy8HZaEsiEVjyPu35ukx2aEpoBIkgWzDcghJbFtEJ39qQms1vC8cECiT6LXsxJsbhkTjJ/fa7Nbac3w/RqS39pKKIXhrf6P2KBDnTeqycPmYfFT08oAA90DBFf8d8/kHHJw2NeRA5+O7yJAdWBHrx2d8YtVC8fvcOMdxS4qqZYHYC5zBB5NgNohPfsevUo7Rk2VADXwI+vWWx1C0cKXWsrx3BmvYL+c4py2LJtxrO9Q0TKjASWioCJOKwXQKkIpMWd11XGmD+9s9mPQbrRljn4xfe59Y=}
