travis:
  secure:
    BINSTAR_TOKEN: ag0ltBnwnMCM68hSR8UvVIWbw7EnrAabyRqDoDtvEJ9trxwcsvVd1ECFM1Sr8JxS3pdSUwOM5BjeRSZyHlYJSBaMn8ei4tBlZnUwcfBxUi0E6kK7+BcMFzM1mmzAFXibZAuX0eYgIlrOsicz/IVK95Ig5zhTaro54ISNjUCxM77yeHl7cEp0BWojM861zId3jGlZuM7OcIh0gbLfwdWlwBjz+98Uu16watIRYrHKToQAo1peBIPzyRHVby6H7mXmwAgxZbdDNjfDsq14lY8fgRFYEh2R9c45eegxsQCemqbqWBDZAZUaYwCk66DOCtfIHfL3JYAvQJ4ckzk8f2MlYnrTYpEKE+BQ37YQKvFn7zBBlGjhWVkZBiXKfZFn/xmbaeEW9VhM/X7QKZpc+0P5VoFGeTUndFPFbBPE6gzJnxFJfILqY7GxCdf2MlfC/vBsAvB0I0iTT+v1p+gIzHY25CQXCeaRP6E60N4tI5kOvWfzWdKRHnuSS2Nsc5grnaSr8h2bk50gQYCH3TpEgdNFxhA2gen35kOgqgF+xxT39B6qVRT6a6MzCBX28Qt2CBvsSCidSVGlPmZzpCvaHWFCwSVCVfggexzj20o98tjveZEI+dI2dW+CosapmIfJ9FB8844YC0EQvpfUHJG0BqJZ2BjX6IGAClGx5xUzH1YAz4M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
